### ISSUE TITLE
Add Vinteum and SP Bitdevs

### ISSUE THREAD

**Issue by storopoli** [supertestnet/good-btc-groups#1]
Can you please add [Vinteum](https://vinteum.org) and [Sao Paulo BitDevs](https://saopaulobitdevs.org/)?

Cc @jaonoctus @lucasdcs @lorenzolfm

Happy to do a PR if you want me to.

**Comment by supertestnet** [comment]
done!

**Comment by jaonoctus** [comment]
ty @supertestnet @storopoli 🇧🇷
